[[redirects]]
  from = "/api"
  to = "https://golandbackend-09fdf720d244.herokuapp.com/api"
  status = 200
  
  from = "/api/points"
  to = "https://golandbackend-09fdf720d244.herokuapp.com/api/points"
  status = 200