[[redirects]]
  from = "/"
  to = "https://golandbackend-09fdf720d244.herokuapp.com"
  status = 200

[[redirects]]
  from = "/api/points"
  to = "https://golandbackend-09fdf720d244.herokuapp.com/api/points"
  status = 200